### ISSUE TITLE
Write Library To Remove Boilerplate

### ISSUE THREAD

**Issue by maniyar1** [frc3324/OffSeason2018#6]
For example: write a DT library that takes encoder ports in the constructor and automatically initializes its setters/getters. It could also instantiate motors and make the DiffDrive setup. This could also be a subsystem extension or something else, ask @maniyar1 or @samf547 if you have questions.

**Comment by samf547** [comment]
Who is this for

**Comment by maniyar1** [comment]
Update: current code without motor implementations is looking like this: https://gist.github.com/maniyar1/171bedaf99f08d8ebd3e31973d82a9f2 
If someone (else) would like to work with it please coordinate with @samf547

**Comment by maniyar1** [comment]
Not enough time to finish and the benefit seems negligible at this point. Will look at after build to see if we want to do this.
